#!/data/data/com.termux/files/usr/bin/bash

# Copyright 2017-2019 by YadominJinta. All rights reserved.
# https://github.com/YadominJinta/atilo has info about the project.
# https://github.com/YadominJinta/atilo/blob/master/CONTRIBUTORS.md Thank you for help.

version="1.7.1 CN"
writer="@YadominJinta @seashell11234455"
support_linux=("alpine" "arch" "centos" "debian" "fedora" "kali" "ubuntu" "ubuntults" "opensuse" )
support_arch=("arm" "aarch64" "amd64" "i386" )
atilo_home=$HOME/.atilo
atilo_tmp=${atilo_home}/tmp

# Create Dir
if [ ! -d ${atilo_home} ]; then
	mkdir -p ${atilo_home}
fi
if [ ! -d ${atilo_tmp} ]; then
	mkdir -p ${atilo_tmp}
fi
function tips()
{
	echo -e "\033[32m$@\033[0m"
}

function error()
{
	echo -e "\033[1;31m$@\033[0m" 1>&2
	exit 1
}

function check_for_req()
{
	tips "[ 检查依赖中 ]"
	requirements=""

	if [ ! -e $PREFIX/bin/tar ]; then
		requirements="${requirements} tar"
	fi

	if [ ! -e $PREFIX/bin/proot ]; then
		requirements="${requirements} proot"
	fi

	if [ ! -e $PREFIX/bin/pv ]; then
		requirements="${requirements} pv"
	fi

	if [ ! -e $PREFIX/bin/curl ]; then
		requirements="${requirements} curl"
	fi

	if [ ! -e $PREFIX/bin/grep ]; then
		requirements="${requirements} grep"
	fi


	if [ ! -z "$requirements" ]; then
		tips "[ 正在安装依赖项 ]"
		pkg install ${requirements} 
	fi
}

function check_for_arch()
{
    architecture=$(uname -m)

    if [ ${architecture} == "aarch64" ]
    then
        time_arch="arm64"
        
    elif [[ ${architecture} =~ .*(arm).* ]]
    then
        time_arch="armhf"
	elif [[ ${architecture} = "i686" ]]
    then
        time_arch="i386"
    elif [[ ${architecture} = "x86_64" ]]
    then
        time_arch="amd64"
    else
        error "[ 未知的架构 ${architecture}]"
	fi

}

function show_moo()
{
    tips '
                 (__) 
                 (oo) 
           /------\/ 
          / |    ||   
         *  /\---/\ 
            ~~   ~~   
..."Have you mooed today?"...
    ' 
}

function show_usage()
{
    tips "Atilo \t ${version}"
    tips "用法: $0 [命令] [参数] \n"
    tips "Atilo 是一个用来帮助你在termux上安装不同的GNU/Linux发行版的bash脚本。"
    tips "命令:"
    tips "list\t\t 列出可用的Linux"
    tips "   --installed   列出已安装的Linux"
    tips "remove\t\t 移除已安装的Linux"
    tips "install\t\t 安装Linux"
    tips "clean\t\t 删除缓存"
    tips "help\t\t 帮助"
	tips "作者 ${writer} "
	tips "本atilo具有超级牛力"
}

function list_linux()
{
	tips "[ 以下为可用的Linux ]"
    for i in ${support_linux[@]}
    do
        tips $i
    done
}

function local_linux()
{
    tips "\n已安装"
    cd ${atilo_home}
    for i in $(ls ./)
    do
        if [ $i != "tmp" ]; then
            tips $i
        fi
    done

}

function remove_linux()
{
	cd ${atilo_home}
	if [ -d ${release_name} ]; then
		chmod -R 0755 ./${release_name}
		rm -rf ./${release_name}
		rm -f $PREFIX/bin/start${release_name}
		tips "[ 删除${release_name}成功 ]"
		exit 0
	else
		error "[ 未能找到 ${release_name} ]"
	fi
}

function select_linux()
{

	case "$1" in
	     fedora)
            aarch64=https://mirrors.tuna.tsinghua.edu.cn/fedora/releases/31/Container/aarch64/images/Fedora-Container-Base-31-1.9.aarch64.tar.xz
		    amd64=https://mirrors.tuna.tsinghua.edu.cn/fedora/releases/31/Container/x86_64/images/Fedora-Container-Base-31-1.9.x86_64.tar.xz
		    if [[ ${time_arch} = "i386" || ${time_arch} = "armhf" ]]; then 
                 error "Fedora 不支持x86和arm架构"
            fi
		    upgrade="dnf makecache"
	    	;;
	    debian)
		    curl -L "https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/debian/buster/${time_arch}/default/" -o tmp.html  >/dev/null 2>&1
		    ttime=`cat tmp.html |tail -n2|head -n1 |cut -d\" -f4`              
	        rm tmp.html
	    	aarch64=https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/debian/buster/arm64/default/${ttime}rootfs.tar.xz
	    	arm=https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/debian/buster/armhf/default/${ttime}rootfs.tar.xz
	    	amd64=https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/debian/buster/amd64/default/${ttime}rootfs.tar.xz
    		i386=https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/debian/buster/i386/default/${ttime}rootfs.tar.xz
    		zip=pJx
	        mirrors="deb http://mirrors.tuna.tsinghua.edu.cn/debian buster main\ndeb http://mirrors.tuna.tsinghua.edu.cn/debian-security/ buster/updates main"
    		mirrorspath="etc/apt/sources.list"
    		upgrade="apt update && apt upgrade"
	    	;;
	    alpine)
            aarch64=https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.10/releases/aarch64/alpine-minirootfs-3.10.0-aarch64.tar.gz 
	    	arm=https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.10/releases/armhf/alpine-minirootfs-3.10.0-armhf.tar.gz
    		amd64=https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.10/releases/x86_64/alpine-minirootfs-3.10.0-x86_64.tar.gz
    		i386=https://mirrors.tuna.tsinghua.edu.cn/alpine/v3.10/releases/x86/alpine-minirootfs-3.10.0-x86.tar.gz
            zip=pzx
    		sh=ash
    		mirrors="http://mirrors.tuna.tsinghua.edu.cn/alpine/v3.10/main\nhttp://mirrors.tuna.tsinghua.edu.cn/alpine/v3.10/community"
    		mirrorspath="etc/apk/repositories"
    		upgrade="apk update && apk upgrade"
	    	;;
    	arch)
    		aarch64=https://mirrors.tuna.tsinghua.edu.cn/archlinuxarm/os/ArchLinuxARM-aarch64-latest.tar.gz
    		arm=https://mirrors.tuna.tsinghua.edu.cn/archlinuxarm/os/ArchLinuxARM-armv7-latest.tar.gz
    		if [[ ${time_arch} = "i386" || ${time_arch} = "amd64" ]];then
                 error "Arch 不支持 x86 及 amd64 架构"
            fi
	    	zip=pzx
    		mirrors="Server = http://mirrors.tuna.tsinghua.edu.cn/archlinuxarm/\$arch/\$repo"
    		mirrorspath="etc/pacman.d/mirrorlist"
    		upgrade="pacman-key --init && pacman-key --populate archlinuxarm "
	    	;;
    	ubuntults)
    		curl -L "https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/ubuntu/bionic/${time_arch}/default/" -o tmp.html >/dev/null 2>&1
    		ttime=`cat tmp.html |tail -n2|head -n1 |cut -d\" -f4`
			rm tmp.html
	        aarch64=https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/ubuntu/bionic/arm64/default/${ttime}rootfs.tar.xz
    		arm=https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/ubuntu/bionic/armhf/default/${ttime}rootfs.tar.xz
    		amd64=https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/ubuntu/bionic/amd64/default/${ttime}rootfs.tar.xz
    		i386=https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/ubuntu/bionic/i386/default/${ttime}rootfs.tar.xz
    		zip=pJx
    		mirrors="deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports bionic main restricted universe multiverse\ndeb http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports bionic-updates main restricted universe multiverse"
    		mirrorspath="etc/apt/sources.list"
    		upgrade="apt update "
    		;;
        ubuntu)
    		curl -L "https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/ubuntu/disco/${time_arch}/default/" -o tmp.html >/dev/null 2>&1
    		ttime=`cat tmp.html |tail -n2|head -n1 |cut -d\" -f4`
    		rm tmp.html
    		aarch64=https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/ubuntu/disco/arm64/default/${ttime}rootfs.tar.xz
	        arm=https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/ubuntu/disco/armhf/default/${ttime}rootfs.tar.xz
    		i386=https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/ubuntu/disco/i386/default/${ttime}rootfs.tar.xz
    		amd64=https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/ubuntu/disco/amd64/default/${ttime}rootfs.tar.xz
    		zip=pJx
    		mirrors="deb http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports disco main restricted universe multiverse\ndeb http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports disco-updates main restricted universe multiverse"
	        mirrorspath="etc/apt/sources.list"
    		upgrade="apt update "
	    	;;
    	kali)
			curl -L "https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/kali/current/${time_arch}/default/" -o tmp.html > /dev/null 2>&1
			ttime=`cat tmp.html |tail -n2|head -n1 |cut -d\" -f4`
			rm tmp.html
			aarch64=https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/kali/current/arm64/default/${ttime}rootfs.tar.xz
	        arm=https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/kali/current/armhf/default/${ttime}rootfs.tar.xz
    		i386=https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/kali/current/i386/default/${ttime}rootfs.tar.xz
    		amd64=https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/kali/current/amd64/default/${ttime}rootfs.tar.xz
			zip=pJx
			mirrors="deb http://mirrors.tuna.tsinghua.edu.cn/kali kali-rolling main non-free contrib"
	        mirrorspath="etc/apt/sources.list"
    		upgrade="apt update "
    		;;
		centos)
			curl -L "https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/centos/7/${time_arch}/default/"  -o tmp.html > /dev/null 2>&1
			ttime=`cat tmp.html |tail -n2|head -n1 |cut -d\" -f4`
			rm tmp.html
			aarch64=https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/centos/7/arm64/default/${ttime}rootfs.tar.xz
        	arm=https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/centos/7/armhf/default/${ttime}rootfs.tar.xz
    		i386=https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/centos/7/i386/default/${ttime}rootfs.tar.xz
    		amd64=https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/centos/7/amd64/default/${ttime}rootfs.tar.xz
			zip=pJx
			upgrade="yum makecache"
			;;
		opensuse)
			curl -L "https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/opensuse/tumbleweed/${time_arch}/default/"  -o tmp.html > /dev/null 2>&1
			ttime=`cat tmp.html |tail -n2|head -n1 |cut -d\" -f4`
			rm tmp.html
			aarch64=https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/opensuse/tumbleweed/arm64/default/${ttime}rootfs.tar.xz
    		i386=https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/opensuse/tumbleweed/i386/default/${ttime}rootfs.tar.xz
    		amd64=https://mirrors.tuna.tsinghua.edu.cn/lxc-images/images/opensuse/tumbleweed/amd64/default/${ttime}rootfs.tar.xz
			zip=pJx
			upgrade="zypper ref"
			;;
    	*)
    		error "[ 不支持的发行版 $1 ]"
    		;;
    esac

}
function clean_tmp()
{
    tips "[  正在清除缓存 ]"
    rm ${atilo_tmp}/*
}
function install_linux()
{
	cd $atilo_tmp
	root=$atilo_home/$release_name
	if [ ! -d ${root} ]; then
		mkdir ${root}
	fi

	tips "[ 正在下载中 ... ]"
	if [ -f ${release_name} ]; then
		tips "[ 跳过下载 ]"
	else
		ls -A | xargs rm -rf 
		curl "${url}" -o ${release_name} --progress-bar -C -
	fi

	tips "[ 解压中 ... ]"
	if [ "${release_name}" == "fedora" ]; then
		tar xf fedora --strip-components=1 --exclude json --exclude VERSION
		pv layer.tar|tar xpC ${root} 2>/dev/null
		rm -f layer.tar
		chmod +w ${root}
		mkdir ${root}/etc/yum.repos.d/bak
		mv ${root}/etc/yum.repos.d/fedora.repo ${root}/etc/yum.repos.d/bak
		mv ${root}/etc/yum.repos.d/fedora-updates.repo ${root}/etc/yum.repos.d/bak
		cat > ${root}/etc/yum.repos.d/fedora.repo <<-EOM
[fedora]
name=Fedora \$releasever - \$basearch
failovermethod=priority
baseurl=https://mirrors.tuna.tsinghua.edu.cn/fedora/releases/\$releasever/Everything/\$basearch/os/
metadata_expire=28d
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-\$releasever-\$basearch
skip_if_unavailable=False
		EOM
		cat > ${root}/etc/yum.repos.d/fedora-updates.repo <<-EOM
[updates]
name=Fedora \$releasever - \$basearch - Updates
failovermethod=priority
baseurl=https://mirrors.tuna.tsinghua.edu.cn/fedora/updates/\$releasever/Everything/\$basearch/
enabled=1
gpgcheck=1
metadata_expire=6h
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-fedora-\$releasever-\$basearch
skip_if_unavailable=False
		EOM
	else
		pv ${release_name} |tar ${zip}C ${root} 2>/dev/null
	fi

	tips "[ 配置中 ...]"
	rm -r ${root}/etc/resolv.conf 2>/dev/null
	echo "nameserver 8.8.8.8" >> ${root}/etc/resolv.conf
	echo "export USER=root" >> ${root}/etc/profile

	if [ ! -z "${mirrors}" ]; then
		cd ${root}
		echo -e "${mirrors}" > ${mirrorspath}
	fi

	cat > ${PREFIX}/bin/start${release_name} <<- EOM
#!/data/data/com.termux/files/usr/bin/bash
cd \$HOME/.atilo/
unset LD_PRELOAD
command="proot"
command+=" --link2symlink"
#command+=" -0"
command+=" -S ${release_name}"
#command+=" -b /system"
command+=" -b /sdcard"
command+=" -b /dev/"
#command+=" -b /sys/"
command+=" -b /proc/"
#uncomment the following line to have access to the home directory of termux
#command+=" -b /data/data/com.termux/files/home"
command+=" -w /root"
command+=" /usr/bin/env -i"
command+=" HOME=/root"
command+=" LANG=C.UTF-8"
command+=" PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin"
command+=" TERM=xterm-256color"
command+=" /bin/${sh} --login"
export PROOT_NO_SECCOMP=1
com="\$@"
if [ -z "\$1" ];then
    exec \$command
else
    \$command -c "\$com"
fi
	EOM
	chmod +x $PREFIX/bin/start${release_name}

	tips "[ 升级中 ... ]"
	start${release_name} ${upgrade}

	tips "[ 全部完成 ]"
    tips "start${release_name} 以开始"
}

function main()
{
	release_name=$2
	case "$1" in
		install|in)
			check_for_arch
			check_for_req
			cd ${atilo_home}
			sh=bash
			select_linux ${release_name}	
			case ${time_arch} in
			   arm64)
			        url=${aarch64}
                ;;
			   armhf)
			        url=${arm}
                ;;
			   i386)
   				    url=${i386}
                ;;
                amd64)
                    url=${amd64}
                ;;
			esac
	        select_linux ${release_name}	
			install_linux
			    ;;
	        remove|rm)
			          remove_linux
			;;
		    list|ls)
                    if [[ $2 == "--installed" ]]; then
                            local_linux
                    else
			            list_linux 
                    fi
			;;
		    help)
		        show_usage
			;;
            clean)
                clean_tmp
            ;;
		    "")
		        show_usage
	            error "[ 请指定一个命令 ]"
		    ;;
		    *)
			error "[ 未知的命令 ]"
			;;
		
	esac
}

main "$@"
